name: activerecord-tidb-adapter ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README*.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README*.md'
      - 'docs/**'

jobs:
  tidb511:
    name: test_activerecord_tidb_v5.1.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://hawkingrei/tind:v5.1.1
        name: __all__
        with:
          args: |
            bash -c "service supervisor start && sleep 10s && bundle install && MYSQL_USER=root MYSQL_HOST=127.0.0.1 MYSQL_PORT=4000 tidb=1 ARCONN=tidb bundle exec rake db:tidb:build && MYSQL_USER=root MYSQL_HOST=127.0.0.1 MYSQL_PORT=4000 tidb=1 ARCONN=tidb bundle exec rake test:tidb"


