name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README*.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README*.md'
      - 'docs/**'

jobs:
  build:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    container: ruby:2.7
    services:
      tidb:
        image: hawkingrei/tind:v5.1.0
        env:
          TIDB_VERSION: v5.1.0
        ports: ["4000:4000"]
    steps:
    - uses: actions/checkout@v2
    - run: bundle install
    - run: apt-get update && apt-get install -y default-mysql-client 
    - run: MYSQL_USER=root MYSQL_HOST=127.0.0.1 MYSQL_PORT=4000 tidb=1 ARCONN=tidb bundle exec rake db:tidb:build
    - run: MYSQL_USER=root MYSQL_HOST=127.0.0.1 MYSQL_PORT=4000 tidb=1 ARCONN=tidb bundle exec rake test:tidb